# -*- coding: utf-8 -*-
"""Model_Classification_latest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zj5HRva3Sa-RpcTh_skTOW2OlxiKGGyS
"""

!pip install git+https://github.com/BakyLedos/fast-bert.git

!cp /content/drive/MyDrive/apex.zip .
!unzip apex.zip

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NVIDIA/apex
# %cd apex
!git checkout 23.05
!pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
!pip install openpyxl
# %cd ..
!pip install sentencepiece

import torch
from fast_bert.data_cls import BertDataBunch
from fast_bert.learner_cls import BertLearner
from fast_bert.data_lm import BertLMDataBunch
from fast_bert.learner_lm import BertLMLearner
from fast_bert.metrics import fbeta, roc_auc
from fast_bert.prediction import BertClassificationPredictor
from pathlib import Path
import pandas as pd
import logging


logger = logging.getLogger()
device_cuda = torch.device("cuda")
# device_mps = torch.device("cpu")

DATA_PATH = Path.cwd()/'data'
LOG_PATH = Path.cwd()/'logs'
MODEL_PATH = Path.cwd()/'model'
LABEL_PATH = Path.cwd()/'labels'

DATA_PATH.mkdir(parents=True, exist_ok=True)
LOG_PATH.mkdir(parents=True, exist_ok=True)
MODEL_PATH.mkdir(parents=True, exist_ok=True)
LABEL_PATH.mkdir(parents=True, exist_ok=True)

# Lecture de la base de donnees et selection des colonnes
data = pd.read_excel("data2.xlsx")
data = data[[c for c in data.columns if c!='Unnamed: 0']]
cols = data.columns.to_list()[7:]
cols.insert(0,'Commentaire')
data = data[cols]

data.head(3)

val_set = data.sample(frac=0.2, replace=False, random_state=42)
train_set = data.drop(index = val_set.index)
print('Nombre de commentaires dans le val_set:',len(val_set))
print('Nombre de commentaires dans le train_set:', len(train_set))
val_set.to_csv(DATA_PATH/'val.csv')
train_set.to_csv(DATA_PATH/'train.csv')

# Creation du fichier labels.txt
labels = data.columns[1:].to_list()
with open(LABEL_PATH/'labels.txt', 'w') as f:
    for i in labels:
        f.write(i + "\n")

# Creation du fichier labels.csv
pd.DataFrame(labels).to_csv(LABEL_PATH/'labels.csv',index=False, header=False)

all_texts = data['Commentaire'].to_list()
print('Nombre de commentaires:', len(all_texts))

"""### Création de LMDataBunch"""

databunch_lm = BertLMDataBunch.from_raw_corpus(
                    data_dir=DATA_PATH,
                    text_list=all_texts,
                    tokenizer='camembert-base',
                    batch_size_per_gpu=16,
                    max_seq_length=512,
                    multi_gpu=False,
                    model_type='camembert-base',
                    logger=logger)

"""### Création de LMLearner"""

lm_learner = BertLMLearner.from_pretrained_model(
                            dataBunch=databunch_lm,
                            pretrained_path='camembert-base',
                            output_dir=MODEL_PATH,
                            metrics=[],
                            device=device_cuda,
                            logger=logger,
                            multi_gpu=False,
                            logging_steps=50,
                            fp16_opt_level="O2")

lm_learner.fit(epochs=30,
            lr=1e-4,
            validate=True,
            schedule_type="warmup_cosine",
            optimizer_type="adamw")

lm_learner.validate()

lm_learner.save_model()

"""# Entrainement du model

### Création de databunch pour la classification
"""

databunch = BertDataBunch(DATA_PATH, LABEL_PATH,
                          tokenizer='camembert-base',
                          train_file='train.csv',
                          val_file='val.csv',
                          label_file='labels.txt',
                          text_col='Commentaire',
                          label_col=['Cohésion Sociale', 'Insecurité', 'Gouvernance économique', 'Gouvernance politique'],
                          batch_size_per_gpu=16,
                          max_seq_length=512,
                          multi_gpu=False,
                          multi_label=True,
                          model_type='camembert-base')

len(databunch.train_dl)

"""### Création de Learner"""

metrics = [{'name': 'fbeta', 'function': fbeta}, {'name': 'roc_auc', 'function': roc_auc}]
OUTPUT_DIR = Path.cwd()/'finetuned_model'

WGTS_PATH = MODEL_PATH/'model_out/pytorch_model.bin'

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_DIR

cl_learner = BertLearner.from_pretrained_model(
                        databunch,
                        pretrained_path=MODEL_PATH/'model_out',
                        metrics=metrics,
                        device=device_cuda,
                        logger=logger,
                        output_dir=OUTPUT_DIR,
                        finetuned_wgts_path=WGTS_PATH,
                        warmup_steps=300,
                        multi_gpu=False,
                        multi_label=True,
                        is_fp16=False,
                        logging_steps=50)

cl_learner.fit(epochs=30,
            lr=9e-5,
            validate=True,
            schedule_type="warmup_cosine",
            optimizer_type="adamw")

cl_learner.validate()

"""### Prédictions"""

cl_learner.save_model()

comments = [
    '''Le Burkina compte plus d’une soixantaine d’ethnies c’est pas seulement avec les mossis que les peuls rencontrent des soucis. Oui c’est vrai que les peuls des milieux ruraux ce sont trop mis a l’écart des autres communautés et font difficilement confiance au autres toujours a s’autostigmatiser''',
    '''Ah ! Ceci ressemble encore à des complaintes qui ne servent à rien . Les affaires sont les affaires. S’ils ont réfusé de vendre leurs armes , c’est que c’etait pas de bonnes affaires pour eux. C’est tout. Maintenant si vous voulez qu’on vende des armes à vos conditions alors que vous n’en produisez pas et que ces partenaires ne sont pas en obligation de se plier à ces conditions, il n’y’a pas à se plaindre. Que dire alors si des partenaires reclamaient que leurs armes ne soient pas payées en dévises courantes mais plutôt en lingots ou mines entiers ? Des situations comme Karma, Yirgou etc ne favorisent pas non plus la vente d’arme à nos pays car certains ne voudraient pas se retrouver embarqués . C’est ce que certains font semblant de ne pas savoir. Or nous savons qu’il faut l’autorisation des instances politiques pour des ventes d’armes dans certains pays
  Aucun de ces "partenaires" n’a pour priorité la satisfaction des réseaux sociaux et de la rue. Donc au lieu de continuer à se plaindre à chaque occasion, chose qui perdra à force de répétition son tranchant, mieux vaudra avancer dans le réalisme et loin de l’influence des tapages de réseaux sociaux.
''',
    '''SOYEZ DIGNE ET AYEZ DE L’HONNEUR MR KYELEM APRES TOUT CE QUE VOUS AVEZ FAIT COMME TAPAGE MEDIATIQUE POUR ETRE NOMME.
La composition du gouvernement vient de sortir. Le vin est tiré et il faut le boire mais à quel prix surtout pour le PM Mr Kyelem.
Nous avons deux observations à faire en ce qui concerne les principes et idéaux  prônés par Mr Kyelem :
1. Voilà ce que disait Mr Kyelem lors d’un débat public sur Mr Bassolma qu’il a accepté dans son gouvernement aujourdhui : « « « « il y avait une différence de style et de fonds entre Bassolma Bazié et Tolé Sagnon. Tolé Sagnon me semblait beaucoup plus convaincu de ce qu’ íl faisait et disait que par rapport à Bssolma Bazié.
Bassolma Bazié est quelqu ‘un, n’est-ce pas, qui était excité etc et ces gens-là …. cad quand vous le voyez dans les interviews etc il semblait quelqu’un d’excité, pas stable etc et moi je me méfie tout de suite de ces gens-là car ça traduit une certaine immaturité psychologique et intellectuelle……..….Quand on est mure on est calme, posé etc on est convaincu de ce que l’on fait. Vous avez vu Tolé Sagnon ici. Tolé Sagnon par exemple exposait ses problèmes calmement mais fermement. C’est comme un certain syndicaliste qui était Nanéma qui dirigeait le SYNTSHA il était aussi calme mais ferme………………………..Ça ne m’a jamais surpris, je n’ai jamais fait confiance à des gens comme ça (Bassolma Bazié)  qui sont capable de tout du pire comme du meilleur, donc moi ça ne m’a pas surpris…. » » » ».
Après ces graves insultes publiques faites par  Mr Kyelem sur Bassolma Bazié, voilà que Mr Bassolma est dans le gouvernement du PM Kyelem. D’abord insulter publiquement quelqu’un est un manque de reste pour la personne insultée et aussi à soi-même.
Comment va-t-il le regarder en face maintenant, ce Bassolma Bazié qu’ íl a qualifié d’excité, de pas stable, immature psychologiquement et intellectuellement, ….je me méfie de lui (Bassolma). Comment Mer Kyelem travaillera-t-il avec Mr Bassolma dans ces conditions ?
Quand on a un minimum d’honneur, de dignité, quand on a foi en ses idéaux et quand on est conséquent envers soi-même, alors Mr Kyelem devrait démissionner de son poste de PM et rendre le tablier.
2. Reconduction de Mme Olivia Rouamba
Mme Roumba est l’antipode des idées sankaristes déjà de par ces frasques à New York l’été dernier. Donc Olivia est contraire même aux idéaux prônes par Mr Kyelem.
Au regard de ses deux éléments si Mr Kyelem avait un minimum d’honneur, de dignité, de foi, il devrait démissionner immédiatement et surtout que Mr Bassolma Bazié a été élevé au poste de Ministre d’Etat apparait comme un désaveu aux idéaux de Mr Kyelem
Que pouvait-on attendre d’un débateur public comme Mr Kyelem ? ''',
]

len(comments)

for comment in comments:
  prediction = cl_learner.predict_batch(comment)[0]
  print(prediction)